# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_prize', models.CharField(max_length=250)),
                ('product_img', models.CharField(max_length=500)),
            ],
        ),
    ]
