# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product_name',
        ),
        migrations.AddField(
            model_name='basket',
            name='product_name',
            field=models.ManyToManyField(to='product.Posts'),
        ),
    ]
