# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170904_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='product_des',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
