# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_posts_product_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='product_des',
            field=models.TextField(max_length=2000),
        ),
    ]
