# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170911_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='product_group',
            field=models.CharField(default='steam', max_length=250),
            preserve_default=False,
        ),
    ]
