# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_posts_product_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='product_group',
            new_name='product_category',
        ),
    ]
