# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20170917_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['product_name']},
        ),
    ]
