# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 12:11
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20170919_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
