# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20170919_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=10, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.Post'),
            preserve_default=False,
        ),
    ]
