# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20170921_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Comment'),
        ),
    ]
