# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_comment_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='children',
            new_name='parent',
        ),
    ]
