# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20170921_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Comment'),
            preserve_default=False,
        ),
    ]
