# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guest_first_name', models.CharField(max_length=10, null=True)),
                ('Guest_last_name', models.CharField(max_length=10, null=True)),
                ('Guest_email', models.EmailField(max_length=50, null=True)),
                ('issue_options', models.CharField(choices=[('co', 'همکاری'), ('pb', 'مشکل در خرید'), ('ag', 'درخواست بازی'), ('o', 'موارد دیگر')], default='co', max_length=2)),
                ('message', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('pro_img', models.FileField(blank=True, null=True, upload_to='uploaded')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_options', models.CharField(choices=[('co', 'همکاری'), ('pb', 'مشکل در خرید'), ('ag', 'درخواست بازی'), ('o', 'موارد دیگر')], default='co', max_length=2)),
                ('message', models.TextField(max_length=250, null=True)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
