# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_profile',
            field=models.FileField(default='settings.DEFAULT_PROFILE_IMG', upload_to=''),
        ),
    ]
