# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userprofile_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_profile',
            new_name='profile_img',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
