# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20170924_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='settings.DEFAULT_PROFILE_IMG', upload_to=''),
        ),
    ]
