# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20170924_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='/armin/default_img_prof.jpg', upload_to=''),
        ),
    ]
