# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20170924_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.FileField(default='settings.DEFAULT_PROFILE_IMG', upload_to=''),
        ),
    ]
