# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 16:09
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20170924_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.FileField(default='settings.IMG_Files/default_img_prof.jpg', storage=django.core.files.storage.FileSystemStorage(location='/armin/shop images/'), upload_to='settings.IMG_Files'),
        ),
    ]
