# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_auto_20170925_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.FileField(default='/armin/shop images/default_img_prof.jpg', upload_to='uploaded'),
        ),
    ]
