# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_auto_20170925_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.FileField(upload_to='uploaded'),
        ),
    ]
