# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_auto_20170925_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.FileField(upload_to='uploaded', default='default_img_prof.jpg'),
        ),
    ]
