# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0034_auto_20170925_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_img',
        ),
    ]
