# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0036_userprofile_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_img',
            new_name='pro_img',
        ),
    ]
