# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 18:12
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0039_auto_20170925_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pro_img',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prof_img',
            field=models.FileField(default='shop/media/default_img_prof.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\armin\\shop\\shop/media'), upload_to='uploaded'),
        ),
    ]
