# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0040_auto_20170925_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='prof_img',
            new_name='pro_img',
        ),
    ]
