# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0044_auto_20170925_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pro_img',
            field=models.FileField(default='', upload_to='uploaded'),
        ),
    ]
