# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 07:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0047_auto_20170926_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='09016126859', max_length=15, validators=[django.core.validators.RegexValidator(regex='0(\\w{10})')]),
            preserve_default=False,
        ),
    ]
