# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 16:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0051_auto_20170928_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='0\\d{10}')]),
        ),
    ]
