# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 04:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_comment_public'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('User', '0053_auto_20170928_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='1', max_length=11, validators=[django.core.validators.RegexValidator(regex='0\\d{10}')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
