# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0059_auto_20171002_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Issue_options',
            field=models.CharField(choices=[('co', 'همکاری'), ('pb', 'مشکل در خرید'), ('ag', 'درخواست بازی'), ('o', 'موارد دیگر')], default='co', max_length=2),
        ),
    ]
