# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0060_auto_20171002_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Issue_options',
            new_name='issue_options',
        ),
    ]
