# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0061_auto_20171002_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='guess_email',
            field=models.EmailField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='guess_first_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='guess_last_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
