# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0062_auto_20171002_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='guess_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
