# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0063_auto_20171002_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_options', models.CharField(choices=[('co', 'همکاری'), ('pb', 'مشکل در خرید'), ('ag', 'درخواست بازی'), ('o', 'موارد دیگر')], default='co', max_length=2)),
                ('message', models.TextField(max_length=250, null=True)),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
