# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0065_auto_20171002_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='GuestMessage',
        ),
        migrations.RenameField(
            model_name='guestmessage',
            old_name='guess_email',
            new_name='Guest_email',
        ),
        migrations.RenameField(
            model_name='guestmessage',
            old_name='guess_first_name',
            new_name='Guest_first_name',
        ),
        migrations.RenameField(
            model_name='guestmessage',
            old_name='guess_last_name',
            new_name='Guest_last_name',
        ),
    ]
